## =========================================================
## 1. Define the local GitHub repository folder
## =========================================================
#install.packages(c("shinylive", "httpuv")) ## pacchetti per convertire il tutto in html

# Main folder of the BIOservicES-toolkit repository on your computer.
# This is the folder tracked by GitHub Desktop and contains app.R,
# the model/data files, and the docs/ folder published by GitHub Pages.
repo_dir <- "C:/Users/luigi.caopinna/OneDrive - CREA/Documents/GitHub/BIOservicES-toolkit"



## =========================================================
## 2. Define the Cloudflare Web Analytics snippet
## =========================================================

# This HTML/JavaScript snippet is provided by Cloudflare Web Analytics.
# It loads the Cloudflare analytics beacon when the public website
# is opened.
#
# The token identifies this website in the Cloudflare Web Analytics
# account. The token is expected to be visible in the public HTML.
#
# This does not modify the statistical models or Shiny calculations.
# It only adds website-traffic analytics to the generated HTML page.
cf_snippet <- paste0(
  "<!-- Cloudflare Web Analytics -->",
  "<script type='module' ",
  "src='https://static.cloudflareinsights.com/beacon.min.js' ",
  "data-cf-beacon='{\"token\": \"5d1085ae6c254261b597f6320f780dea\"}'>",
  "</script>",
  "<!-- End Cloudflare Web Analytics -->"
)



## =========================================================
## 3. Export the Shiny app as a Shinylive website
## =========================================================

# Convert the local Shiny application into a browser-based
# Shinylive/WebR application.
#
# appdir:
# folder containing app.R and the files required by the app.
#
# destdir:
# folder where the static website is generated.
# GitHub Pages is configured to publish docs/.
#
# wasm_packages = TRUE:
# include/download WebAssembly-compatible versions of the R packages
# required by the application so that they can run in the browser.
#
# template_params:
# insert the Cloudflare Analytics snippet directly into the HTML
# generated by Shinylive. Therefore the analytics code is automatically
# restored every time the website is exported.
shinylive::export(
  appdir = repo_dir,
  destdir = file.path(repo_dir, "docs"),
  wasm_packages = TRUE,
  template_params = list(
    include_after_body = cf_snippet
  )
)



## =========================================================
## 4. Create the .nojekyll file for GitHub Pages
## =========================================================

# The .nojekyll file tells GitHub Pages to serve the generated
# static files directly without Jekyll processing.
file.create(
  file.path(repo_dir, "docs", ".nojekyll")
)



## =========================================================
## 5. Check that the essential website files exist
## =========================================================

# Expected result: TRUE
file.exists(
  file.path(repo_dir, "docs", "index.html")
)

# Expected result: TRUE
file.exists(
  file.path(repo_dir, "docs", ".nojekyll")
)



## =========================================================
## 6. Verify that Cloudflare Analytics was inserted
## =========================================================

# Read the generated index.html into R.
index_html <- paste(
  readLines(
    file.path(repo_dir, "docs", "index.html"),
    warn = FALSE
  ),
  collapse = "\n"
)

# Confirm that the Cloudflare beacon is present.
#
# Expected result:
# [1] TRUE
grepl(
  "static.cloudflareinsights.com/beacon.min.js",
  index_html,
  fixed = TRUE
)



## =========================================================
## 7. Start a local web server for testing
## =========================================================

# Serve the generated docs/ folder locally so that the website
# can be tested before publishing it.
#
# The R console remains occupied until the server is stopped.
#
# Use the PUBLIC GitHub Pages URL, rather than localhost,
# when checking whether Cloudflare Analytics is collecting data.
httpuv::runStaticServer(
  file.path(repo_dir, "docs")
)

